version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: immutable-grafana
    build:
      context: ./grafana
      dockerfile: Dockerfile
    ports:
      - "3000:3000"